### ISSUE TITLE
Remove save_all_data_flag?

### ISSUE THREAD

**Issue by DarkTyr** [DarkTyr/squid_ssa_char#5]
Should we remove the save_all_data flag from the SSA_data_collection.py script?
At the very least, set it to be True by default

Pro: 
    - don't have to remember to set it
    - space is extremely cheap

Cons:
    - can no longer email the data to people if needed

Thoughts?

**Comment by emaloney19** [comment]
Why does removing this flag mean we cant email the data? Due to the increase in size? What if instead of removing it we default it to true and you have to choose to make it false if you know youre going to want to email the data since without it being true we cant do Rdyn plots at all.

**Comment by DarkTyr** [comment]
17 MB without compression, once compressed with zip, it is a little over 1 MB. Size is not an issue. 
Now the RDyn plots, now that would be an issue. Two options there are to save all data from the sweep or be intelligent and save the IC_Max VPhi and one step below it. 

I believe in this case, save all the data all the time. 
Remove the flag and all references to it.
