### ISSUE TITLE
Add meta information to PDF outputs

### ISSUE THREAD

**Issue by DarkTyr** [DarkTyr/squid_ssa_char#7]
It would be very useful to have the data file name and/or date the data was taken that has been processed in the generated PDF report. Could also add the User (QA Tester), System name, SSA type and design.

**Comment by emaloney19** [comment]
So I think we can just add a one line table to the end of the pdf (after the last plot) set up the same as the starting table but some of this info is stored in the class and some isnt? I can pull the qa_name from the class but the system name is never named anywhere even tho the class has a spot for it and the SSA type and design are both named in the test config but never stored in the class? How do I rectify this without losing/breaking everything.
